
@api = http://localhost:3001

### Get all character 
GET {{api}}/character

### Filter character 
GET {{api}}/character?data={"status": "unknown"}
# content-type: application/json

# {
#     "filterValues": {
#         "status": "Alive"
#     }
# }
###"name": "Rick",                                              INPUT
###"species": "",                                               INPUT
###"type": "",                                                  INPUT
###"status": "Alive", //Alive || Dead || Unknow *               CHECKBOXS
###"gender": "female" //Female || Male || Genderless || Unknow  CHECKBOXS

### Get character by id
GET {{api}}/character/1

### Create character
POST {{api}}/character
content-type: application/json

{
    "name": "jorge",
    "status": "Alive",
    "gender": "Genderless"
}

### Delete characters
DELETE  {{api}}/character

### Delete character
DELETE  {{api}}/character/63f3faeacabd85ce5d69e018

### Update character
PATCH   {{api}}/character/63f3faeacabd85ce5d69e018
content-type: application/json

{
    "fields":{
        "name": "Pepito",
        "image": "aasdasdas"
    }
}

### Get all species 
GET {{api}}/species